---
functional:
  - Пользователь должен иметь возможность регистрироваться и входить в систему
  - Зарегистрированный пользователь может создавать игру и приглашать других пользователей или играть с ботом
  - Система должна обеспечивать одновременное редактирование задачи для двух игроков с отображением кода соперника в реальном времени
  - Пользователь может выбирать уровень и тип задачи для соревнования
  - После окончания игры отображается результат
  - Присутствует система рейтингов и лидерборд
  - Есть возможность играть с друзьями по ссылке
non-functional:
  - Сайт оптимизирован для высокой скорости загрузки и работы
  - Приложение безопасно хранит и передает пользовательские данные
  - Интерфейс адаптирован для мобильных устройств
  - Система поддерживает нагрузку не менее 1000 одновременных пользователей без деградации качества работы
  - Web-приложение протестировано на последних версиях популярных браузеров
implicit:
  - Требуется возможность легко встраивать новые задачи и языки программирования
  - Проект должен быть прост в сопровождении и доработке силами сообщества
  - Должен быть реализован механизм оповещений/уведомлений
  - Время отклика и синхронизации кода между участниками должно быть минимальным
