---
functional:
  - Пользователь должен иметь возможность регистрироваться и входить в систему
  - Пользователь должен иметь возможность входить в систему через аккаунты Github
  - Пользователь должен иметь возможность входить в систему через аккаунты Discord
  - Гость (незарегистрированный пользователь) должен иметь возможность играть с ботом, без сохранения игрового прогресса и без участия в системе рейтингов
  - Зарегистрированный пользователь может создавать игру и играть со случайным другим зарегистрированным пользователем
  - Зарегистрированный пользователь может создавать игру и приглашать конкретного зарегистрированного пользователя по его никнейму
  - Зарегистрированный пользователь может создавать игру и выбирать бота в качестве соперника
  - Пользователю доступны различные режимы игры (стандартный 1v1, тренировочный режим и турниры)
  - Система должна поддерживать организацию и проведение турниров
  - В интерфейсе активной игры пользователь должен иметь возможность выбрать язык программирования из списка поддерживаемых для решения текущей задачи
  - Система должна обеспечивать одновременное редактирование задачи для двух игроков с отображением кода соперника в реальном времени
  - Пользователь может выбирать уровень сложности задачи и ее тип для соревнования
  - Пользователи должны иметь возможность просматривать историю редактирование кода
  - После окончания игры система должна отображать сводку результатов
  - Присутствует система рейтингов и лидерборд
  - Зарегистрированный пользователь должен иметь доступ к своему профилю
  - Пользователи должны иметь возможность наблюдать за текущими играми других участников
  - В лобби должен быть доступен общий чат для общения пользователей
  - В лобби должен отображаться список активных игр/ожидающих игроков
non-functional:
  - Сайт оптимизирован для высокой скорости загрузки и работы
  - Приложение безопасно хранит и передает пользовательские данные
  - Интерфейс адаптирован для мобильных устройств
  - Система поддерживает нагрузку не менее 1000 одновременных пользователей без деградации качества работы
  - Web-приложение протестировано на последних версиях популярных браузеров
  - Интерфейс приложения должен быть доступен как минимум на английском языке, с возможностью добавления других языков
implicit:
  - Требуется возможность легко встраивать новые задачи, типы задач и языки программирования
  - Проект должен быть прост в сопровождении и доработке силами сообщества
  - Должен быть реализован механизм оповещений/уведомлений
  - Время отклика и синхронизации кода между участниками должно быть минимальным
  - Система должна иметь средства для предотвращения читерства
